--- #YAML:1.0
name:                Audio-Ardour-Irc
version:             0.10
abstract:            Infra red remote control of the Ardour DAW.
license:             ~
author:              
    - Noel Darlow <cpan@aperiplus.co.uk>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::HomeDir:                 0.67
    Net::LibLO:                    0.06
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
